version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  sentiment_app:
    build: .
    depends_on:
      - kafka
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: python run_all.py
